name: Generate Image List

on:
  push:
    paths:
      - 'imagenes/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate imagenes.json
        run: |
          echo "[" > imagenes.json
          ls imagenes | grep -E '\.(jpg|png|jpeg|webp)$' | sed 's/^/"/' | sed 's/$/",/' >> imagenes.json
          sed -i '$ s/,$//' imagenes.json
          echo "]" >> imagenes.json

      - name: Commit imagenes.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add imagenes.json
          git commit -m "Actualizar lista de im√°genes" || echo "No changes to commit"
          git push
